name: lifetalk_editor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
      sdk: flutter
  
  cart_stepper: ^4.3.0
  go_router: ^14.6.0
  syncfusion_flutter_sliders: ^28.2.11
  youtube_player_flutter: ^9.1.1
  flutter_fancy_tree_view: ^1.6.0
  intry: ^0.3.2
  nakama: ^1.0.5
  package_info_plus: ^8.2.1
  device_info_plus: ^11.3.0
  advertising_id: ^2.7.0
  shared_preferences: ^2.5.2
  flutter_timezone: ^4.1.0
  get_it: ^8.0.0
  grpc: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/texts/

icons_launcher:
  image_path: ../screenshots/logo.png
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    macos:
      enable: true